app = "layla-rsrc3g"
primary_region = "bom"

[build]

[env]
  NODE_ENV = "production"

[processes]
  app = "npm start"

[mounts]
  source = "bot_data"
  destination = "/app/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1